taylorwilsdon/google_workspace_mcp

- LICENSE
- README.md
- core/server.py
- gcalendar/calendar_tools.py
- gdrive/drive_tools.py
- gmail/__init__.py
- gmail/gmail_tools.py
- main.py
This pull request introduces comprehensive Google Drive and Gmail integration into the MCP server. It:
- Defines new OAuth scopes for Drive and Gmail in `core/server.py`.
- Updates the combined `SCOPES` list to include Drive (readonly + per-file) and Gmail (readonly + send).
- Enhances existing calendar tools with clearer LLM guidance, parameter docs, and return types.
- Adds a new `gdrive` package with tools for searching, listing, reading, and creating Drive files.
- Adds a new `gmail` package with tools for searching messages and retrieving message content.
- Registers the new tools by importing `gdrive.drive_tools` and `gmail.gmail_tools` in `main.py`.
- **core/server.py**
- Added constants:
- `DRIVE_READONLY_SCOPE`, `DRIVE_FILE_SCOPE`
- `GMAIL_READONLY_SCOPE`, `GMAIL_SEND_SCOPE`
- …
> feat: Add Support for Google Drive and Gmail Operations

- README.md
- auth/google_auth.py
- config/google_config.py
- core/server.py
- gcalendar/calendar_tools.py
- gdrive/drive_tools.py
- gmail/gmail_tools.py
This PR **centralises Google Workspace OAuth configuration and unifies authentication** across Calendar, Drive, and Gmail tools.
Key benefits:
* Single source-of-truth for scopes and redirect-state mapping
* Less duplicated helper code
* Cleaner README examples and credential path (`.credentials/you@example.com.json`)
---
* **Config**
* New `config/google_config.py` contains all scope constants, the combined `SCOPES`, and `OAUTH_STATE_TO_SESSION_ID_MAP`.
* **Auth Layer**
* `auth/google_auth.py`
* Adds `CONFIG_CLIENT_SECRETS_PATH` auto-detection.
* Replaces `start_auth_flow` with an **async** version returning `types.CallToolResult`.
* Drops hard-coded `DEFAULT_REDIRECT_URI`; value is now passed from the server.
* **Server**
* Removes local scope constants; now imports everything from …
> refac: oauth / authentication

- README.md
- config/google_config.py
- core/server.py
- gdocs/docs_tools.py
- gdrive/drive_tools.py
- main.py
This pull request adds full Google Docs API integration to the Google Workspace MCP Server. The integration enables users to search for Google Docs, read document content, list documents within folders, and create new documents - all through the MCP protocol.
- Added Google Docs API scopes in [`config/google_config.py`](config/google_config.py:28-29)
- Created new module [`gdocs/docs_tools.py`](gdocs/docs_tools.py) with Google Docs functionality
- Integrated the new module in [`main.py`](main.py:41)
- Cleaned up commented code in [`core/server.py`](core/server.py)
- Updated Drive scopes configuration in [`config/google_config.py`](config/google_config.py:57-58)
The PR adds four new MCP tools for Google Docs integration:
1. **`search_docs`**: Search for Google Docs by name across a user's …
> feat: Google Docs support

- config/google_config.py
- core/server.py
- gmail/gmail_tools.py
Add new tool to create Gmail draft messages with optional recipients. This allows users to save email drafts at any stage of composition without requiring all fields to be completed.
- Implements Gmail draft API integration
- Makes "to" field optional for flexibility
- Uses GMAIL_COMPOSE_SCOPE for authentication
- Maintains existing project patterns for error handling and logging
> Add draft_gmail_message MCP tool

- README.md
- auth/google_auth.py
- core/streamable_http.py
- gcalendar/calendar_tools.py
- gdrive/drive_tools.py
- gmail/gmail_tools.py
- main.py
This pull request introduces a `--single-user` command-line flag to the MCP server, allowing it to operate without session-to-OAuth mapping and use any available credentials found in the `.credentials` directory. Additionally, it improves the robustness of extracting user email for logging from credentials across Google Calendar, Drive, and Gmail tools.
**Key Changes:**
-   **Single-User Mode:**
-   Added `--single-user` flag to [`main.py`](main.py) using `argparse`.
-   Introduced `MCP_SINGLE_USER_MODE` environment variable to signal single-user mode activation.
-   Implemented [`_find_any_credentials()`](auth/google_auth.py:41) in [`auth/google_auth.py`](auth/google_auth.py) to locate and load any credential file for single-user use.
-   Updated …
> feat: Single User Mode -> trusted environment to bypass session requirements

- auth/google_auth.py
- gcalendar/calendar_tools.py
- gdocs/docs_tools.py
- gdrive/drive_tools.py
- gmail/gmail_tools.py
feat: Centralize Google Workspace Authentication
This pull request implements a centralized authentication helper for Google Workspace MCP tools, significantly reducing code duplication and improving maintainability.
**Key Changes:**
- **Centralized Authentication Helper**: A new asynchronous function, [`get_authenticated_google_service()`](auth/google_auth.py:442), has been added to [`auth/google_auth.py`](auth/google_auth.py:1). This function handles the common logic for obtaining authenticated Google service clients (Gmail, Calendar, Drive, Docs) based on a required `user_google_email` and necessary scopes.
- **Removed Session Dependency**: The brittle in-memory session cache (`_SESSION_CREDENTIALS_CACHE`) and the `mcp_session_id` parameter have been removed from the authentication …
> enh: Refactor authentication to deduplicate redundant logic 

- gmail/gmail_tools.py
- Add _generate_gmail_web_url() helper function using #all for universal Gmail access
- Update search_gmail_messages to return XML-structured output with index attributes
- Include clickable Gmail web interface URLs for both messages and threads
- Maintain backward compatibility with existing Message/Thread ID usage
- Improve manual verification capabilities for users when multiple threads have same subject
> feat: enhance Gmail search with XML structure and web interface links

- README.md
- auth/google_auth.py
- auth/oauth_callback_server.py
- auth/scopes.py
- auth/service_decorator.py
- core/server.py
* Created auth/scopes.py with all the scope constants and configuration
* Updated auth/service_decorator.py to import from auth/scopes.py and removed duplicate scope definitions
* Updated all files (core/server.py, auth/google_auth.py, auth/oauth_callback_server.py) to
import from auth/scopes.py
* Removed the old config/google_config.py file
The structure is now clean with no circular imports:
- auth/scopes.py: Contains all scope constants and OAUTH_STATE_TO_SESSION_ID_MAP
- auth/service_decorator.py: Contains the decorator logic and imports scopes from auth/scopes.py
- All other files import scopes from auth/scopes.py
This eliminates the duplication and consolidates all scope definitions in a single, dedicated module without any circular dependency issues.
> refac: deduplicate scopes config 

- README.md
Currently the only way to find out about configuring the secrets location is by reading the code at https://github.com/taylorwilsdon/google_workspace_mcp/blob/ec480a2aee3eaa76497d9bb75e9269e0594db428/auth/google_auth.py#L30-L39
So, just add a quick note in the relevant part of the README.md
> Explain GOOGLE_CLIENT_SECRETS in README.md

- auth/service_decorator.py
- core/utils.py
- gcalendar/calendar_tools.py
- gchat/chat_tools.py
- gdocs/docs_tools.py
- gdrive/drive_tools.py
- gforms/forms_tools.py
- gsheets/sheets_tools.py
- gslides/slides_tools.py
This pull request introduces two major refactoring improvements to enhance the robustness, maintainability, and developer experience of the Google Workspace MCP server.
Previously, any tool using the `@require_google_service` decorator (e.g., `create_event`) required the calling LLM to redundantly include a `service` parameter in its request. This was because the `FastMCP` server inspected the function's raw signature, saw the `service` parameter meant for internal injection, and incorrectly exposed it as a required field in the public API schema. This led to unnecessary `422 Unprocessable Entity` errors and brittle tool definitions.
The `@require_google_service` decorator in `auth/service_decorator.py` has been refactored to solve this problem elegantly. It now:
1.  Inspects the …
> refac: service decorator & httperror handler

- README.md
- auth/google_auth.py
- auth/oauth_callback_server.py
- core/server.py
- uv.lock
This pull request introduces a more flexible and secure method for configuring Google OAuth credentials by adding support for environment variables. This is now the recommended approach, especially for production and containerized deployments, as it avoids storing secrets in version control.
*   **Environment Variable Configuration**:
*   You can now configure the server using `GOOGLE_OAUTH_CLIENT_ID` and `GOOGLE_OAUTH_CLIENT_SECRET` environment variables.
*   The credential loading priority is:
1.  Environment Variables
2.  `GOOGLE_CLIENT_SECRETS` path
3.  `client_secret.json` in the root directory.
*   **Updated Authentication Flow**:
*   A new function [`auth/google_auth.py:88`](auth/google_auth.py:88) was added to load secrets from the environment.
*   The …
> feat: support google client secret injection via environment variables

- gmail/gmail_tools.py
Closes https://github.com/taylorwilsdon/google_workspace_mcp/issues/115#issuecomment-3109333693
This PR addresses critical SSL connection pool exhaustion issues in the Gmail batch API implementation that were causing frequent failures with errors like `[SSL] record layer failure`, `[SSL: UNEXPECTED_RECORD]`, and `IncompleteRead` exceptions.
The root cause was identified as:
- Connection pool exhaustion from creating too many concurrent SSL connections
- Missing proper connection management and reuse
- Aggressive parallel processing in fallback scenarios that worsened the problem
- **Reduced Batch Sizes**: Decreased from 100 to 25 items per batch to limit concurrent SSL connections
- **Sequential Fallback Processing**: Replaced `asyncio.gather` with sequential processing to prevent SSL …
> fix: SSL Connection Pool Exhaustion in Gmail Batch API

- README.md
- auth/google_auth.py
- auth/oauth_callback_server.py
- auth/scopes.py
- core/server.py
- uv.lock
Until we implement the oauth2.1 branch, this is unnecessary and causing issues like https://github.com/taylorwilsdon/google_workspace_mcp/issues/119
> Remove mcp_session_id from project entirely

- auth/google_auth.py
- auth/oauth_callback_server.py
- core/server.py
- main.py
- uv.lock
Noticed you don't get specific info (port unavailable etc) if the stdio built in minimal oauth callback server fails to start up, this fixes that.
> enh: add more elegant handling for oauth server startup in stdio mode

- gcalendar/calendar_tools.py
- uv.lock
Closes:
https://github.com/taylorwilsdon/google_workspace_mcp/issues/129
https://github.com/taylorwilsdon/google_workspace_mcp/issues/130
For create_event function:
- Added add_google_meet: bool = False parameter
- When True, creates a Google Meet conference using the conferenceData
field with hangoutsMeet type
- Generates a unique request ID using UUID for conference creation
- Sets conferenceDataVersion=1 in the API call when Google Meet is
requested
- Enhanced confirmation message to include Google Meet link when available
For modify_event function:
- Added add_google_meet: Optional[bool] = None parameter
- When True, adds Google Meet conference to existing event
- When False, removes existing Google Meet conference
- When None, preserves existing conference data
- Always sets …
> feat: Google Meet support for create and edit event, fix move attributes

- gslides/slides_tools.py
The getThumbnail API call was using incorrect parameter name `thumbnailPropertiesImageSize` instead of the flattened parameter names required by the Google API Python client:
- `thumbnailProperties_thumbnailSize`
- `thumbnailProperties_mimeType`
> Fix Google Slides getThumbnail API parameter names

- Dockerfile
- README.md
- auth/fastmcp_google_auth.py
- auth/google_auth.py
- auth/google_remote_auth_provider.py
- auth/oauth_common_handlers.py
- auth/oauth_config.py
- docker-compose.yml
- helm-chart/workspace-mcp/templates/NOTES.txt
- helm-chart/workspace-mcp/values.yaml
- main.py
- manifest.json
- smithery.yaml
This pull request primarily updates how the application's base URL and port are handled throughout the authentication and configuration code, and adds a Docker Compose configuration for local development. The most significant changes involve removing the port from the `base_url` variable, which simplifies URL management and ensures consistency. Additionally, a new `docker-compose.yml` file is introduced to streamline running the service locally.
Configuration and URL handling improvements:
* Removed the port from the `base_url` in `auth/oauth_config.py` and updated its usage in `auth/google_remote_auth_provider.py` to ensure URLs are consistently constructed without appending the port. [[1]](diffhunk://#diff-13f6b130be79ba2fa7350c792f996a8135e9c5538d37dc3e92e02b9119f82902L28-R28) …
> Refactor base URL handling and add Docker Compose for local development

- gtasks/tasks_tools.py
fixes #139
add comment from https://developers.google.com/workspace/tasks/reference/rest/v1/tasks/list about the parameter show_completed
This doc comment is provided to the LLM in tool information, helping it know how to show completed tasks.
> explain that when show_completed is set, show_hidden should also be set

- gtasks/tasks_tools.py
resolves #204 by differentiating subtasks for top-level tasks
Also:
* Creates placeholder parents for orphaned subtasks, grouping them together even though their parent isn't available.
* Performs sorting of tasks in a simpler  way.
* Fixes mypy type warnings in tasks_tools.py so that mypy runs clean on this one file. See #194 for more info about type checking.
> feat: show subtask hierarchy

- gcalendar/calendar_tools.py
- Add 'transparency' parameter to create_event and modify_event functions
- Supports 'opaque' (Busy) and 'transparent' (Available/Free) modes
- Validates input and logs transparency setting or warning
- Defaults to None, preserving existing Google Calendar behavior
Provides more granular control over event scheduling and visibility.
> feat(gcalendar): Add event transparency option
